language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "mostrovoi-github"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.organization=mostrovoi-github \
       -Dsonar.login=${SONARQUBE_TOKEN}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
  