language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: mostrovoi-github
    token: 
      secure: "K3T3BW+oofXB7wQouwFeVFUg5RHuKaQf5FM9uIn6V6rS8CwaHCwhEs9dQKtCdWqah2ti8/4pWjVqwPo3UJe5eY15eVA3tu5e7c6cdFlXx0L3YuHQtk7S+XctWK6tHhu79ux47SYDviehJCJk7zjFMqXCdxSHPDL1VS5v7AAGnrGm6k14yKkczsauK/Jy2FnXlUUt4XOQCdrpg+uK0YgmRICk5mozleyo3orG8bisD4Eb+FIZbpFo6LojJdLF3HdXakkXg3ccY6WKYDpAY79EsWvUoGPM6Lw4yiN1k6+9Dhm7cYQXE/DbprB87cIDmRCnvNjQfsQ05beZvG1Ox9ahXku4oW5qYHnYlm9WNgTeEL8FE1N6ofE6cJDYQ9d8oUNNBFj69WbJZH3leMn4qfH1RRyU5UtP/sd4tb1y+65mMiJxZKxFDMXNcaLqmvKSPz4qgOJwaCopJrVSCpKfZNE12U/WfwOGHIysBMCW05I8ZTTeT9OP/SGuP24Hn7TWrYpa31hNWNtu6FmfwwgHKukVUZ4h+b9l//nEnpUn3Ct00UxOsq8nGLRccwmnSftnAWFRCEQ/dPWXmDRdE7mRcvUKr+v5xuLgqO/AHMT4j1FePEsfSzTfTaxVWi+GqFzDQncRqhbmhOtBoEPmVQbDbvIhoYMDZmrXB2OLjob9G7VjsK4="
jdk:
- oraclejdk8
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
